name: Build & Deploy MkDocs + PDF

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    # Use your prebuilt image from the manual workflow
    container:
      image: ghcr.io/${{ github.repository }}/pdf-builder:latest
      # If private image, uncomment:
      # credentials:
      #   username: ${{ github.actor }}
      #   password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Build PDF
        run: make pdf
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: hs3.pdf

  build-site:
    needs: build-pdf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

        # Install your site deps (adjust as needed)
      - name: Install MkDocs
        run: |
          pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Ensure files dir exists
        run: mkdir -p docs/files

      - name: Download PDF artifact into docs/
        uses: actions/download-artifact@v4
        with:
          name: pdf
          path: docs/files

      - name: Build site
        run: mkdocs build --site-dir site

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build-site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
