name: Build PDF

on:
  push:          # every branch
  pull_request:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Override image tag (default: latest)"
        required: false
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest

    # If the GHCR image is PUBLIC:
    container:
      image: ghcr.io/${{ github.repository }}/pdf-builder:${{ inputs.image_tag || vars.PDF_IMAGE_TAG || 'latest' }}

    # If the GHCR image is PRIVATE, uncomment this block instead of the above:
    # permissions:
    #   contents: read
    #   packages: read
    # container:
    #   image: ghcr.io/${{ github.repository }}/pdf-builder:${{ inputs.image_tag || vars.PDF_IMAGE_TAG || 'latest' }}
    #   credentials:
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Build PDF
        run: make pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: hs3.pdf   # adjust to your Makefile output
