name: Build PDF

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install make (Alpine)
        run: apk add --no-cache make

      - name: Build PDF
        run: make pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: hs3.pdf    # adjust if different
