name: Publish PDF Builder Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to publish (e.g. latest, v1, my-feature)"
        required: true
        default: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # required to push to GHCR
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/pdf-builder:${{ github.event.inputs.tag }}
          # Optional caching (speeds up subsequent builds):
          cache-from: type=gha
          cache-to: type=gha,mode=max
